export ENV=$HOME/.kshrc

#xsetroot -solid Gray10 &
xsetroot -solid Gray15 &
#xsetroot -solid Gray20 &
#xsetroot -solid MidnightBlue &

# For background wallpaper (add feh)
#~/.fehbg &

#xterm -bg black -fg white +sb &
xterm -bg black -fg green +sb &
xterm -bg black -fg orange +sb &
#xterm -bg black -fg green  -fa terminus -fs 12 &
#xterm -bg black -fg orange -fa terminus -fs 12 &

#xclock -geometry 128x128-1+1 &
xclock -geometry 192x192-1+1 -bg black -fg orange -hands orange -highlight gold3 &

# Select window manager below

# 1. cwm
#/usr/X11R6/bin/cwm

# 2. twm
#/usr/X11R6/bin/twm

# 3. fvwm
/usr/X11R6/bin/fvwm

# 4. fluxbox (added)
#/usr/local/bin/startfluxbox

# 5. spectrwm (added)
#/usr/local/bin/spectrwm
